#!/bin/bash

# Debian bootstrapper
# Author: Peter Deak (hyper80@gmail.com)
# License: GPL,  No warrantly, use at you own risk!

#export DMC_DONTRUNCONF="dontrunconf"

# ######################################################################################

export DMC_DONTASK=""                  # Can be "dontask"
export DMC_SERVERNAME="buster"
export DMC_DOMAIN="local"              # domain without hostname
export DMC_TARGETREGION="none"         # Territory/Region "us" or "hu" or ...
export DMC_FSTYPE="zfs"                # zfs or ext4
export DMC_MAC=""                      # 00:12:23:ab:cd:ef
export DMC_IFACE="ether0"              # lan0 ether0 wan1
export DMC_IPSRC="dhcp"                # "dhcp" or "static"
export DMC_IPADDRESS="192.168.1.1/24"
export DMC_GWADDRESS="192.168.1.254"
export DMC_DNSADDRESS="192.168.1.254"
export DMC_BOOTTYPE="bios"             # "bios" or "efi"
export DMC_DISKS=""                    # Disk block devices "sda sdb sdc" which meant /dev/sda and /dev/sdb ...
export DMC_RAIDSPEC=""                 # "" or "mirror" or "raidz" or "raidz1" or "raidz2" or "raidz3"
export DMC_POOL="zfs_pool"
export DMC_ZFSCOMP="off"               # "off" or "lz4"
export DMC_DIST="debian"
export DMC_RELEASE="buster"
export DMC_PACKAGES=""                 # extra packages to install
export DMC_ADDITIONALLOCALE=""         # For example: "hu_HU"
export DMC_TZAREAANDNAME="America/New_York"
export DMC_KEYMODELLAYOUTVAR="pc105/us"
export DMC_NEEDDOCKER="n"              # "n" or "y"
export DMC_SSHPERMITROOT="yes"         # "no" or "prohibit-password" or "yes"

export DMC_ROOTPSWD=""

# ######################################################################################

export DMC_RESERVERDDISKTAIL="20M"     # Reserved space on disk end
export DMC_LVMVOLFILE="lvm_volumes"    # The file which contains the table of lvm volumes
export DMC_ZFSDTSETFILE="zfs_datasets" # The file which contains the table of zfs datasets