#!/bin/bash

# Debian bootstrapper
# Author: Peter Deak (hyper80@gmail.com)
# License: GPL,  No warrantly, use at you own risk!

echo ">>> Calling lib_inchroot"
source /lib_inchroot
compgen -A function
echo ">>> do a full-upgrade"

apt update
apt -y full-upgrade

export LC_CTYPE=C

debconf-set-selections <<EOF
locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8, hu_HU.UTF-8 UTF-8
locales locales/default_environment_locale select C.UTF-8
debconf debconf/priority select critical
debconf debconf/frontend select Noninteractive
tzdata tzdata/Areas select ${TZAREA}
tzdata tzdata/Zones/${TZAREA} select ${TZNAME}
EOF

apt -y install locales
sed -e 's/^# hu_HU.UTF-8 UTF-8/hu_HU.UTF-8 UTF-8/' -e 's/^# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' -i /etc/locale.gen
echo "${TZAREA}/${TZNAME}" > /etc/timezone
ln -sf /usr/share/zoneinfo/${TZAREA}/${TZNAME} /etc/localtime
dpkg-reconfigure debconf -f noninteractive -p critical
locale-gen
update-locale LANG=C.UTF-8
apt -y install --no-install-recommends linux-image-amd64 linux-headers-amd64 linux-libc-dev:amd64 ${PACKAGES}

apt -y install zfsutils-linux zfs-zed dkms zfs-dkms zfs-initramfs spl-dkms spl

apt -y install gdisk dosfstools git rsync keyboard-configuration kbd man

echo ">>> Position i5"
compgen -A function

dm_grub_setbiosboot

echo ">>> Position i6"
compgen -A function

dm_swap_swaponzfs

echo ">>> Position i7"
compgen -A function

dm_zfs_setzfsparameters

echo ">>> Position i8"
compgen -A function

dm_set_rootpassword

echo ">>> Position i9"
compgen -A function


apt -y install ssh

echo ">>> Position i10"
compgen -A function

dm_set_docker
if test "${NEEDDOCKER}" "=" "y"
then
    dm_set_docker
fi


