#!/bin/bash

# Debian bootstrapper
# Author: Peter Deak (hyper80@gmail.com)
# License: GPL,  No warrantly, use at you own risk!

source /lib_inchroot

apt update
apt -y full-upgrade

export LC_CTYPE=C

debconf-set-selections <<EOF
locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8, hu_HU.UTF-8 UTF-8
locales locales/default_environment_locale select C.UTF-8
debconf debconf/priority select critical
debconf debconf/frontend select Noninteractive
tzdata tzdata/Areas select ${TZAREA}
tzdata tzdata/Zones/${TZAREA} select ${TZNAME}
EOF

apt -y install locales
sed -e 's/^# hu_HU.UTF-8 UTF-8/hu_HU.UTF-8 UTF-8/' -e 's/^# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' -i /etc/locale.gen
echo "${TZAREA}/${TZNAME}" > /etc/timezone
ln -sf /usr/share/zoneinfo/${TZAREA}/${TZNAME} /etc/localtime
dpkg-reconfigure debconf -f noninteractive -p critical
locale-gen
update-locale LANG=C.UTF-8
apt -y install --no-install-recommends linux-image-amd64 linux-headers-amd64 linux-libc-dev:amd64 ${PACKAGES}

if test "${FSTYPE}" = "zfs"
then
    apt -y install zfsutils-linux zfs-zed dkms zfs-dkms zfs-initramfs spl-dkms spl
fi

apt -y install gdisk dosfstools git rsync keyboard-configuration kbd man

dm_grub_setbiosboot

if test "${FSTYPE}" = "zfs"
then
    dm_swap_swaponzfs
    dm_zfs_setzfsparameters
fi    

if test "${FSTYPE}" = "ext4"
then
    dm_swap_swaponlvm
fi

dm_set_rootpassword

apt -y install ssh

dm_set_docker
if test "${NEEDDOCKER}" "=" "y"
then
    dm_set_docker
fi


