#!/bin/bash

function dm_grub_setbiosboot {
    DISKDEVS=$(for disk in ${DISKS} ; do echo -n "/dev/${disk} " ; done | sed -e 's@ /@, /@g')
    echo "grub-pc grub-pc/install_devices multiselect ${DISKDEVS}" | debconf-set-selections
    apt -y install grub-pc
    update-initramfs -u -k all
    update-grub
}

function dm_swap_swaponzfs {
    zfs create -V 1G -b $(getconf PAGESIZE) -o compression=off -o logbias=throughput -o sync=always -o primarycache=metadata -o secondarycache=none -o com.sun:auto-snapshot=false ${POOL}/swap
    mkswap /dev/zvol/${POOL}/swap
    echo "/dev/zvol/${POOL}/swap none swap defaults 0 0" >> /etc/fstab
}

function dm_swap_swaponlvm {
    mkswap /dev/${POOL}/${POOL}_swap
    echo "/dev/${POOL}/${POOL}_swap none swap defaults 0 0" >> /etc/fstab
}

function dm_zfs_setzfsparameters {
    zfs set quota=1G ${POOL}/tmp
    zfs set quota=11G ${POOL}/var
    zfs set quota=3G ${POOL}/var/cache
    zfs set quota=1G ${POOL}/var/lib
    zfs set quota=5G ${POOL}/var/log
    zfs set quota=1G ${POOL}/var/spool
    zfs set quota=1G ${POOL}/var/tmp
    zfs set quota=10G ${POOL}/home
    zfs set refreservation=2G ${POOL}/ROOT/${DIST}
    zfs set reservation=10G ${POOL}/ROOT
    zfs set refquota=5G ${POOL}/ROOT/${DIST}
    zfs set reservation=1G ${POOL}/root
    zfs set reservation=3G ${POOL}/var
    zfs set reservation=1G ${POOL}/var/lib
    zfs set reservation=1G ${POOL}/var/log

    zfs set acltype=posixacl ${POOL}
}

function dm_set_rootpassword {
    echo -e "${ROOTPSWD}\n${ROOTPSWD}" | passwd root
}

function dm_set_docker {
    apt -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian ${RELEASE} stable"
    apt update
    apt-cache policy docker-ce
    apt -y install docker-ce
}