#!/bin/bash

# Debian bootstrapper
# Author: Peter Deak (hyper80@gmail.com)
# License: GPL,  No warrantly, use at you own risk!

if test "${DONTRUNCONF}" "!=" "dontrunconf"
then
    . conf
fi

source ./lib

# #########################################################################
if test "${DONTASK}" "!=" "dontask"
then
    dm_ask_settings
fi

export PARTTYPE="EF02" # bios
if test "${BOOT}" = "EFI"
then
    PARTTYPE="EF00" # efi
fi

apt update
apt -y full-upgrade

if test "${FSTYPE}" = "zfs"
then
    dm_zfs_zfsforlive
fi

dm_disk_partitioning

mkdir -p /target

if test "${FSTYPE}" = "zfs"
then
    dm_zfs_makefilesystem
fi

if test "${FSTYPE}" = "ext4"
then
    dm_ext4_makefilesystem
fi

dm_fs_ensuretmprights

debootstrap ${RELEASE} /target

dm_fs_ensuretmprights
dm_set_hostname
dm_net_networksettings
dm_set_sourceslist
dm_console_settings

if test "${FSTYPE}" = "ext4"
then
    dm_ext4_filesystemsettings
fi

mount --rbind /dev /target/dev
mount --rbind /proc /target/proc
mount --rbind /sys /target/sys
cp ./inchroot /target/
cp ./lib_inchroot /target/
chmod +x /target/inchroot
chmod +x /target/lib_inchroot

chroot /target /inchroot
rm /target/inchroot
rm /target/lib_inchroot

umount -Rfl /target/dev
umount -Rfl /target/sys
umount -Rfl /target/proc

if test "${FSTYPE}" = "zfs"
then
    dm_zfs_detachfilesystem
fi
if test "${FSTYPE}" = "ext4"
then
    dm_ext4_detachfilesystem
fi

sync

echo " ============================================================= "
echo " = It seems my work is over, Your system is ready to boot    = "
echo " ============================================================= "
