#!/bin/bash

# Debian bootstrapper
# Author: Peter Deak (hyper80@gmail.com)
# License: GPL,  No warrantly, use at you own risk!

if test "${DONTRUNCONF}" "!=" "dontrunconf"
then
    . conf
fi

source ./lib

# #########################################################################
if test "${DONTASK}" "!=" "dontask"
then
    dm_ask_settings
fi

export PARTTYPE="EF02" # bios
if test "${BOOT}" = "EFI"
then
    PARTTYPE="EF00" # efi
fi

apt update
apt -y full-upgrade

dm_zfs_zfsforlive
dm_disk_partitioning

mkdir -p /target

dm_zfs_makefilesystem

chmod 1777 /target/tmp
chmod 1777 /target/var/tmp

debootstrap ${RELEASE} /target

dm_set_hostname
dm_net_networksettings
dm_set_sourceslist
dm_console_settings

mount --rbind /dev /target/dev
mount --rbind /proc /target/proc
mount --rbind /sys /target/sys
cp ./inchroot /target/
cp ./lib_inchroot
chmod +x /target/inchroot

chroot /target /inchroot
rm /target/inchroot
rm /target/lib_inchroot

umount -Rfl /target/dev
umount -Rfl /target/sys
umount -Rfl /target/proc

zpool export ${POOL}
sync

echo " ============================================================= "
echo " = It seems my work is over, Your system is ready to boot    = "
echo " ============================================================= "
