#!/bin/bash

set -e

function dmf_ask_ifacename {
    local IFACE_R
    read -e -p "Name of the configurable network interface [${DMC_IFACE}]:" IFACE_R
    if test -n "${IFACE_R}"
    then
        DMC_IFACE="${IFACE_R}"
    fi
}

dmf_ask_ifacename
