#!/bin/bash

set -e

function dmf_ask_macaddress {
    local MAC_R
    if test -z "${DMC_MAC}"
    then
        DMC_MAC=$(ip addr | grep link/ether | awk '{print $2}')
    fi
    read -e -p "MAC address of the configurable network interface [${DMC_MAC}]:" MAC_R
    if test -n "${MAC_R}"
    then
        DMC_MAC="${MAC_R}"
    fi
}

dmf_ask_macaddress
