#!/bin/bash

function dmf_ask_keyboard {
    local KEYMODELLAYOUTVAR_R
    read -e -p "Keyboard model/layout/variant [${KEYMODELLAYOUTVAR}]:" KEYMODELLAYOUTVAR_R
    if test -n "${KEYMODELLAYOUTVAR_R}"
    then
        KEYMODELLAYOUTVAR="${KEYMODELLAYOUTVAR_R}"
    fi
}

dmf_ask_keyboard