#!/bin/bash

function dmf_ask_fscompression {
    local ZFSCOMP_R
    if test "${DMC_FSTYPE}" = "zfs"
    then
        read -e -p "The zfs compression <off|lz4> [${DMC_ZFSCOMP}]:" ZFSCOMP_R
        if test -n "${ZFSCOMP_R}"
        then
            DMC_ZFSCOMP="${ZFSCOMP_R}"
        fi
    fi
}

dmf_ask_fscompression
