#!/bin/bash

function dmf_ask_boottype {
    local BOOTTYPE_R
    read -e -p "Set the boot type of the system <bios|efi> [${DMC_BOOTTYPE}]:" BOOTTYPE_R
    if test -n "${BOOTTYPE_R}"
    then
        DMC_BOOTTYPE="${BOOTTYPE_R}"
    fi
}

dmf_ask_boottype
