#!/bin/bash

set -e

function dmf_ask_raidspec {
    local DISKNUM
    local RAIDSPEC_R
    DISKNUM=$(echo "${DMC_DISKS}"|wc -w)

    if test "${DISKNUM}" "-eq" "1"
    then
        DMC_RAIDSPEC=""
    fi
    if test "${DISKNUM}" "-eq" "2"
    then
        DMC_RAIDSPEC="mirror"
    fi
    if test "${DISKNUM}" "-ge" "3"
    then
        DMC_RAIDSPEC="raidz"
    fi

    if test "${DISKNUM}" "-ge" "2"
    then
        read -e -p "Raid type of the disk array <empty|mirror|raidz> [${DMC_RAIDSPEC}]:" RAIDSPEC_R
        if test -n "${RAIDSPEC_R}"
        then
            DMC_RAIDSPEC="${RAIDSPEC_R}"
        fi
    fi
}

dmf_ask_raidspec
