#!/bin/bash

function dmf_ask_password {
    local r1pwd
    local r2pwd
    read -e -s -p "Password for root:" r1pwd
    echo -e "\n"
    read -e -s -p "Password for root again:" r2pwd

    if test "${r1pwd}" = "${r2pwd}"
    then
        ROOTPSWD="${r1pwd}"
    else
        echo -e "\nPassword mismatch, exiting..."
        exit 1
    fi
}

dmf_ask_password
