#!/bin/bash

set -e

function dmf_ask_domain {
    local DOMAIN_R
    read -e -p "Network domain name [${DMC_DOMAIN}]:" DOMAIN_R
    if test -n "${DOMAIN_R}"
    then
        DMC_DOMAIN="${DOMAIN_R}"
    fi
}

dmf_ask_domain