#!/bin/bash

function dmf_ask_poolname {
    local POOL_R
    if test "${DMC_POOL}" "=" "zfs_pool"
    then
        DMC_POOL="${DMC_SERVERNAME}_pool"
    fi
    read -e -p "The zfs pool name [${DMC_POOL}]:" POOL_R
    if test -n "${POOL_R}"
    then
        DMC_POOL="${POOL_R}"
    fi
}

dmf_ask_poolname
