#!/bin/bash

function dmf_ask_raidspec {
    local DISKNUM
    local RAIDSPEC_R
    DISKNUM=$(echo "${DISKS}"|wc -w)

    if test "${DISKNUM}" "-eq" "1"
    then
        RAIDSPEC=""
    fi
    if test "${DISKNUM}" "-eq" "2"
    then
        RAIDSPEC="mirror"
    fi
    if test "${DISKNUM}" "-ge" "3"
    then
        RAIDSPEC="raidz"
    fi
    read -e -p "Raid type of the disk array <empty|mirror|raidz> [${RAIDSPEC}]:" RAIDSPEC_R
    if test -n "${RAIDSPEC_R}"
    then
        RAIDSPEC="${RAIDSPEC_R}"
    fi
}

dmf_ask_raidspec
