#!/bin/bash

function dmf_ask_targetregion {
    local TARGETREGION_R
    local REGIONLINE
    local REGION_TOADDLOCALE
    local REGION_TOTIMEZONE
    local REGION_TOKEYBOARD
    read -e -p "Target territory/region [${DMC_TARGETREGION}]:" TARGETREGION_R
    if test -n "${TARGETREGION_R}"
    then
        DMC_TARGETREGION="${TARGETREGION_R}"
        if test "${DMC_TARGETREGION}" "!=" "none"
        then

            if test -f regiondefaults
            then
                REGIONLINE=$(cat regiondefaults| grep "^${DMC_TARGETREGION} ")
                if test -n "${REGIONLINE}"
                then
                    REGION_TOADDLOCALE=$(echo ${REGIONLINE} | awk '{print $2}')
                    REGION_TOTIMEZONE=$(echo ${REGIONLINE} | awk '{print $3}')
                    REGION_TOKEYBOARD=$(echo ${REGIONLINE} | awk '{print $4}')
                    if test -n "${REGION_TOTIMEZONE}"
                    then
                        DMC_TZAREAANDNAME="${REGION_TOTIMEZONE}"
                    fi
                    if test -n "${REGION_TOKEYBOARD}"
                    then
                        DMC_KEYMODELLAYOUTVAR="${REGION_TOKEYBOARD}"
                    fi
                    if test -n "${REGION_TOADDLOCALE}"
                    then
                        if test "${REGION_TOADDLOCALE}" "!=" "none"
                        then
                            DMC_ADDITIONALLOCALE="${REGION_TOADDLOCALE}"
                        fi
                    fi
                fi
            else
                echo "Cannot load regiondefaults file!"
                exit 1;
            fi

        fi
    fi
}

dmf_ask_targetregion
