#!/bin/bash

set -e

function dmf_ask_timezones {
    local TZAREAANDNAME_R
    read -e -p "Timezone area/name [${DMC_TZAREAANDNAME}]:" TZAREAANDNAME_R
    if test -n "${TZAREAANDNAME_R}"
    then
        DMC_TZAREAANDNAME="${TZAREAANDNAME_R}"
    fi
}

dmf_ask_timezones