#!/bin/bash

set -e

function dmf_ask_servername {
    local SERVERNAME_R
    read -e -p "Hostname of the computer [${DMC_SERVERNAME}]:" SERVERNAME_R
    if test -n "${SERVERNAME_R}"
    then
        DMC_SERVERNAME=${SERVERNAME_R}
    fi
}

dmf_ask_servername
