#!/bin/bash

function dmf_chr_grubsetefiboot {
    local FIRSTDISK
    FIRSTDISK=""
    DISKDEVS=$(for disk in ${DISKS} ; do echo -n "/dev/${disk} " ; done | sed -e 's@ /@, /@g')
    echo "grub-pc grub-pc/install_devices multiselect ${DISKDEVS}" | debconf-set-selections

    apt -y install grub-efi grub-efi-amd64 efibootmgr dosfstools rsync

    for disk in ${DISKS}; do
        if test ! -n "${FIRSTDISK}"
            then
                FIRSTDISK="/dev/${disk}1"
                mkfs.fat -F 32 -n efi-boot /dev/${disk}1
                if test ! -d "/boot/efi"
                then
                    mkdir -p /boot/efi
                fi
                mount /dev/${disk}1 /boot/efi
                grub-install --efi-directory=/boot/efi --target=x86_64-efi /dev/$disk
                echo -e "/dev/${disk}1\t/boot/efi\tvfat\tnoauto,noatime 1 2" >> /dev/fstab
            else
                mkfs.fat -F 32 -n efi-boot /dev/${disk}1
                if test ! -d "/boot/${disk}-efi"
                then
                    mkdir -p /boot/${disk}-efi
                fi
                mount /dev/${disk}1 /boot/${disk}-efi
                rsync -a /boot/efi/ /boot/${disk}-efi
            fi
    done
    update-initramfs -u -k all
    update-grub
}

dmf_chr_grubsetefiboot
