#!/bin/bash

function dmf_chr_docker {
    apt -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian ${DMC_RELEASE} stable"
    apt update
    apt-cache policy docker-ce
    apt -y install docker-ce
}

dmf_chr_docker