#!/bin/bash

function dmf_chr_zfsswapon {
    zfs create -V 1G -b $(getconf PAGESIZE) -o compression=off -o logbias=throughput -o sync=always -o primarycache=metadata -o secondarycache=none -o com.sun:auto-snapshot=false ${POOL}/swap
    mkswap /dev/zvol/${POOL}/swap
    echo "/dev/zvol/${POOL}/swap none swap defaults 0 0" >> /etc/fstab
}

dmf_chr_zfsswapon
