#!/bin/bash

set -e

function dmf_disk_partitioning {
    for disk in ${DMC_DISKS}; do
    sgdisk -Z \
        -n1:1M:+512M -t1:${DMC_RESPARTTYPE} -c1:${disk}1-${DMC_BOOTTYPE} \
        -n2:0:-${DMC_RESERVERDDISKTAIL} -t2:${DMC_DATPARTTYPE} -c2:${disk}-data /dev/${disk}
    done

    sleep 10
    lsblk
    sleep 5
    echo "Available named partitions:"
    ls /dev/disk/by-partlabel/
}

dmf_disk_partitioning
