#!/bin/bash

function dmf_ext4_makefilesystem {
    local PARTS
    local DISKNUM

    PARTS=$(for disk in ${DMC_DISKS} ; do echo -n "/dev/disk/by-partlabel/${disk}-data "; done)

    export DMC_ONEDATAPART=""
    DISKNUM=$(echo "${DMC_DISKS}"|wc -w)
    if test "${DISKNUM}" "-eq" "1"
    then
        echo ">>> Using single disk without raid..."
        STRIPPEDDISKNAME=$(echo ${DMC_DISKS} | sed 's/ //g')
        DMC_ONEDATAPART="/dev/disk/by-partlabel/${STRIPPEDDISKNAME}-data"
    fi
    if test "${DISKNUM}" "-ge" "2"
    then
        echo ">>> Create a soft raid array..."
        DMC_ONEDATAPART="/dev/md0"
        mdadm --create ${DMC_ONEDATAPART} \
              --level=${DMC_RAIDSPEC} \
              --raid-devices=${DISKNUM} \
              --force --run --metadata=0.90 ${PARTS}
    fi

    sleep 2

    echo ">>> Create LVM on disk(s)..."
    pvcreate -ff --yes ${DMC_ONEDATAPART}
    sleep 2
    vgcreate ${DMC_POOL} ${DMC_ONEDATAPART}
    sleep 2

    echo ">>> Create volumes on LVM ..."
    cat lvm_volumes | grep -v '^#' | grep -v '^\s*$' | \
    while IFS= read -r line; do
        LIN_LVNAME=$(echo ${line} | awk '{print $2}')
        LIN_MNTPOINT=$(echo ${line} | awk '{print $3}')
        LIN_LVSIZE=$(echo ${line} | awk '{print $4}')
        LIN_LVSIZE_FILT=$(echo ${LIN_LVSIZE} | grep '%')
        LIN_LVSIZE_SWITCH="-l"
        if test "${LIN_LVSIZE_FILT}" "=" ""
        then
            LIN_LVSIZE_SWITCH="-L"
        fi
        echo " >>> Create logical volume ..."
        echo " lvcreate --yes -n ${DMC_POOL}_${LIN_LVNAME} ${LIN_LVSIZE_SWITCH} ${LIN_LVSIZE} ${DMC_POOL}"
        lvcreate --yes -n ${DMC_POOL}_${LIN_LVNAME} ${LIN_LVSIZE_SWITCH} ${LIN_LVSIZE} ${DMC_POOL}
    done

    sleep 2
    echo ">>> Formatting ext4 filesystems..."
    cat lvm_volumes | grep -v '^#' | grep -v '^\s*$' | \
    while IFS= read -r line; do
        LIN_LVNAME=$(echo ${line} | awk '{print $2}')
        LIN_MNTPOINT=$(echo ${line} | awk '{print $3}')
        LIN_FSFORMTYPE=$(echo ${line} | awk '{print $5}')
        if test "${LIN_MNTPOINT}" "!=" "swap"
        then
            EXTFOURTYPE=""
            if test "${LIN_FSFORMTYPE}" "!=" "none"
            then
                EXTFOURTYPE="-T ${LIN_FSFORMTYPE}"
            fi
            echo " >>> Format logical volume ..."
            echo " mkfs.ext4 ${EXTFOURTYPE} -F /dev/mapper/${DMC_POOL}-${DMC_POOL}_${LIN_LVNAME}"
            mkfs.ext4 ${EXTFOURTYPE} -F /dev/mapper/${DMC_POOL}-${DMC_POOL}_${LIN_LVNAME}
        fi
    done

    # FSUUIDOF_ROOT=$(blkid -s UUID -o value /dev/mapper/${DMC_POOL}-${DMC_POOL}_vol_root)
    # FSUUIDOF_VAR=$(blkid -s UUID -o value /dev/mapper/${DMC_POOL}-${DMC_POOL}_vol_var)
    # FSUUIDOF_VARLOG=$(blkid -s UUID -o value /dev/mapper/${DMC_POOL}-${DMC_POOL}_vol_varlog)

    echo ">>> Mounting filesystems..."
    cat lvm_volumes | grep -v '^#' | grep -v '^\s*$' | sort | \
    while IFS= read -r line; do
        LIN_LVNAME=$(echo ${line} | awk '{print $2}')
        LIN_MNTPOINT=$(echo ${line} | awk '{print $3}')
        if test "${LIN_MNTPOINT}" "!=" "swap"
        then
            TEMPORALLY_DIR="/target$(echo ${LIN_MNTPOINT} | sed 's/^\/$//')"
            mkdir -p ${TEMPORALLY_DIR}
            mount /dev/mapper/${DMC_POOL}-${DMC_POOL}_${LIN_LVNAME} ${TEMPORALLY_DIR}
        fi
    done
}

dmf_ext4_makefilesystem
