#!/bin/bash

function dmf_ext4_filesystemsettings {
    local DISKNUM
    DISKNUM=$(echo "${DISKS}"|wc -w)

    if test "${DISKNUM}" "-ge" "2"
    then
        mdadm --detail --scan > /target/etc/mdadm.conf
    fi

    cat ${DMC_LVMVOLFILE} | grep -v '^#' | grep -v '^\s*$' | sort | \
    while IFS= read -r line; do
        LIN_SEQNUM=$(echo ${line} | awk '{print $1}')
        LIN_LVNAME=$(echo ${line} | awk '{print $2}')
        LIN_MNTPOINT=$(echo ${line} | awk '{print $3}')
        LIN_MNTOPTS=$(echo ${line} | awk '{print $6}')
        if test "${LIN_MNTPOINT}" "!=" "swap"
        then
            if test "${LIN_MNTOPTS}" "=" ""
            then
                LIN_MNTOPTS="defaults"
            fi
            echo -e "/dev/mapper/${DMC_POOL}-${DMC_POOL}_${LIN_LVNAME} ${LIN_MNTPOINT}\text4\t${LIN_MNTOPTS} 0       ${LIN_SEQNUM}" >> /target/etc/fstab
        fi
    done
}

dmf_ext4_filesystemsettings
