#!/bin/bash

set -e

# Debian bootstrapper
# Author: Peter Deak (hyper80@gmail.com)
# License: GPL,  No warrantly, use at you own risk!

export LANG=C
export LC_CTYPE=C

if test "${DMC_DONTRUNCONF}" "!=" "dontrunconf"
then
    . ./conf
fi

# #########################################################################
if test "${DMC_DONTASK}" "!=" "dontask"
then
    . ./lib/dm_ask_settings
fi

. ./lib/dm_oset_derivedsettings
. ./lib/dm_uni_efullupgrade
. ./lib/dm_uni_installtools

if test "${DMC_FSTYPE}" = "zfs"
then
    . ./lib/dm_zfs_zfsforlive
fi

. ./lib/dm_disk_partitioning

if test "${DMC_FSTYPE}" = "zfs"
then
    . ./lib/dm_zfs_makefilesystem
fi

if test "${DMC_FSTYPE}" = "ext4"
then
    . ./lib/dm_ext4_makefilesystem
fi

. ./lib/dm_oset_ensuretmprights
. ./lib/dm_oset_debootstrap
. ./lib/dm_oset_ensuretmprights
. ./lib/dm_oset_hostname
. ./lib/dm_oset_networksettings
. ./lib/dm_oset_sourceslist
. ./lib/dm_oset_consolesettings

if test "${DMC_FSTYPE}" = "ext4"
then
    . ./lib/dm_ext4_filesystemsettings
    . ./lib/dm_ext4_lvmswapon
fi

. ./lib/dm_oset_mapdevprocsys
. ./lib/dm_main_startchroot
. ./lib/dm_oset_unmapdevprocsys

if test "${DMC_SSHKEYTOAUTHORIZEDKEYS}" "!=" ""
then
    if test -f "${DMC_SSHKEYTOAUTHORIZEDKEYS}"
    then
        mkdir -p /target/root/.ssh/
        cat ${DMC_SSHKEYTOAUTHORIZEDKEYS} >> /target/root/.ssh/authorized_keys
    fi
fi

if test "${DMC_FSTYPE}" = "zfs"
then
    . ./lib/dm_zfs_detachfilesystem
fi
if test "${DMC_FSTYPE}" = "ext4"
then
    . ./lib/dm_ext4_detachfilesystem
fi

sync
echo " ============================================================= "
echo " = It seems my work is over, Your system is ready to boot    = "
echo " ============================================================= "

if test "${DMC_NEEDREBOOT}" "=" "y"
then
    sleep 1
    reboot -f
else
    echo " Run \"reboot -f\" to boot your system!"
fi
