#!/bin/bash

function dmf_oset_networksettings {
    local FTOW
    echo "127.0.1.1 ${SERVERNAME}.${DOMAIN} ${SERVERNAME}" >> /target/etc/hosts

    FTOW="/target/etc/systemd/network/10-persistent-net.link"
    echo -e "[Match]\nMACAddress=${MAC}\n"                > ${FTOW}
    echo -e "[Link]\nName=${IFACE}"                       >> ${FTOW}

    FTOW="/target/etc/network/interfaces"
    echo -e "# The loopback interface"                    > ${FTOW}
    echo -e "auto lo\niface lo inet loopback"             >> ${FTOW}
    echo -e ""                                            >> ${FTOW}
    echo -e "# Other interface files"                     >> ${FTOW}
    echo -e "source-directory /etc/network/interfaces.d"  >> ${FTOW}

    if test "${IPSRC}" = "static"
    then
        FTOW="/target/etc/network/interfaces.d/${IFACE}"
        echo -e "allow-hotplug ${IFACE}"                 > ${FTOW}
        echo -e "iface ${IFACE} inet static"             >> ${FTOW}
        echo -e "\taddress ${IPADDRESS}"                 >> ${FTOW}
        echo -e "\tgateway ${GWADDRESS}"                 >> ${FTOW}
        echo -e "\tdns-nameservers ${DNSADDRESS}"        >> ${FTOW}
        echo -e "\tdns-search ${DOMAIN}"                 >> ${FTOW}

        echo "nameserver ${DNSADDRESS}" > /target/etc/resolv.conf
    fi

    if test "${IPSRC}" = "dhcp"
    then
        FTOW="/target/etc/network/interfaces.d/${IFACE}"
        echo -e "allow-hotplug ${IFACE}"               > ${FTOW}
        echo -e "iface ${IFACE} inet dhcp"             >> ${FTOW}
    fi
}

dmf_oset_networksettings
