#!/bin/bash

function dmf_oset_derivedsettings {

    export PARTTYPE="EF02" # bios
    if test "${BOOTTYPE}" = "efi"
    then
        PARTTYPE="EF00" # efi
    fi

    export TZAREA=$(echo ${TZAREAANDNAME} | cut -d '/' -f1 )
    export TZNAME=$(echo ${TZAREAANDNAME} | cut -d '/' -f2 )

    export KEYMODEL=$(echo ${KEYMODELLAYOUTVAR} | cut -d '/' -f1 )
    export KEYLAYOUT=$(echo ${KEYMODELLAYOUTVAR} | cut -d '/' -f2 )
    export KEYVARIANT=$(echo ${KEYMODELLAYOUTVAR} | cut -d '/' -f3 )
}

dmf_oset_derivedsettings