#!/bin/bash

function dmf_oset_sourceslist {
    local FTOW
    FTOW="/target/etc/apt/sources.list"
    echo -e "deb http://deb.debian.org/debian/ ${DMC_RELEASE} main non-free contrib" > ${FTOW}
    echo -e "deb http://security.debian.org/ ${DMC_RELEASE}/updates main contrib non-free" >> ${FTOW}
    echo -e "deb http://deb.debian.org/debian/ ${DMC_RELEASE}-updates main contrib non-free" >> ${FTOW}
}

dmf_oset_sourceslist
