#!/bin/bash

function dmf_zfs_makefilesystem {
    PARTS=$(for disk in ${DISKS} ; do echo -n "/dev/disk/by-partlabel/${disk}-data "; done)

    mkdir -p /target
    zpool create -f \
        -o ashift=12 \
        -O atime=off \
        -O canmount=off \
        -O compression=${ZFSCOMP} \
        -O normalization=formD \
        -O mountpoint=/ \
        -R /target ${POOL} ${RAIDSPEC} ${PARTS}

    sleep 1
    echo "================== ZPOOL CREATED =================="
    zpool status
    sleep 2

    zfs create -o canmount=off -o mountpoint=none ${POOL}/ROOT
    zfs create -o canmount=noauto -o mountpoint=/ -o exec=on -o setuid=on -o devices=on ${POOL}/ROOT/${DIST}
    zfs mount ${POOL}/ROOT/${DIST}
    zpool set bootfs=${POOL}/ROOT/${DIST} ${POOL}

    zfs set exec=off ${POOL}
    zfs set setuid=off ${POOL}
    zfs set devices=off ${POOL}

    zfs create -o canmount=off ${POOL}/var
    zfs create -o canmount=off ${POOL}/var/lib
    zfs create ${POOL}/var/lib/apt
    zfs create -o exec=on ${POOL}/var/lib/dpkg
    zfs create ${POOL}/var/log
    zfs create -o com.sun:auto-snapshot=false ${POOL}/var/tmp
    zfs create -o com.sun:auto-snapshot=false ${POOL}/var/cache
    zfs create ${POOL}/var/spool
    zfs create -o com.sun:auto-snapshot=false -o exec=on ${POOL}/tmp
    zfs create -o exec=on ${POOL}/root
    zfs create -o mountpoint=/home ${POOL}/home
    zfs create -o mountpoint=/srv ${POOL}/srv
}

dmf_zfs_makefilesystem
