#!/bin/bash

function dmf_zfs_makefilesystem {
    local PARTS
    PARTS=$(for disk in ${DMC_DISKS} ; do echo -n "/dev/disk/by-partlabel/${disk}-data "; done)

    mkdir -p /target
    zpool create -f \
        -o ashift=12 \
        -O atime=off \
        -O canmount=off \
        -O compression=${DMC_ZFSCOMP} \
        -O normalization=formD \
        -O mountpoint=/ \
        -R /target ${DMC_POOL} ${DMC_RAIDSPEC} ${PARTS}

    sleep 1
    echo "================== ZPOOL CREATED =================="
    zpool status
    sleep 2

    zfs create -o canmount=off -o mountpoint=none ${DMC_POOL}/ROOT
    zfs create -o canmount=noauto -o mountpoint=/ -o exec=on -o setuid=on -o devices=on ${DMC_POOL}/ROOT/${DMC_DIST}
    zfs mount ${DMC_POOL}/ROOT/${DMC_DIST}
    zpool set bootfs=${DMC_POOL}/ROOT/${DMC_DIST} ${DMC_POOL}

    zfs set exec=off ${DMC_POOL}
    zfs set setuid=off ${DMC_POOL}
    zfs set devices=off ${DMC_POOL}

    zfs create -o canmount=off ${DMC_POOL}/var
    zfs create -o canmount=off ${DMC_POOL}/var/lib
    zfs create ${DMC_POOL}/var/lib/apt
    zfs create -o exec=on ${DMC_POOL}/var/lib/dpkg
    zfs create ${DMC_POOL}/var/log
    zfs create -o com.sun:auto-snapshot=false ${DMC_POOL}/var/tmp
    zfs create -o com.sun:auto-snapshot=false ${DMC_POOL}/var/cache
    zfs create ${DMC_POOL}/var/spool
    zfs create -o com.sun:auto-snapshot=false -o exec=on ${DMC_POOL}/tmp
    zfs create -o exec=on ${DMC_POOL}/root
    zfs create -o mountpoint=/home ${DMC_POOL}/home
    zfs create -o mountpoint=/srv ${DMC_POOL}/srv
}

dmf_zfs_makefilesystem
